const examplesData = [ 
	// { href: "examples/atomic-example", name: "atomic-example", category: "css" },
	  { href: "examples/box-model", name: "box-model", category: "css" },
	// { href: "examples/checkbox-toggle.html", name: "checkbox-toggle.html", category: "css" },
	// { href: "examples/checkbox-toggle2.html", name: "checkbox-toggle2.html", category: "css" },
	  { href: "examples/flex-properties", name: "flex-properties", category: "css" },
	  { href: "examples/inputs.html", name: "inputs.html", category: "css" },
	// { href: "examples/loja-menu", name: "loja-menu", category: "css" },
	 { href: "examples/relative-sizes", name: "relative-sizes", category: "css" },
	// { href: "examples/relativity", name: "relativity", category: "css" },
	// { href: "examples/responsive-grid", name: "responsive-grid", category: "css" },
	  { href: "examples/responsive-images", name: "responsive-images", category: "css" },
	// { href: "examples/responsive-tables", name: "responsive-tables", category: "css" },
	// { href: "examples/scss", name: "scss", category: "css" },
	// { href: "examples/scss.zip", name: "scss.zip", category: "css" },
	// { href: "examples/selectors", name: "selectors", category: "css" },
	// { href: "examples/sports-card", name: "sports-card", category: "css" },
	// { href: "examples/typography", name: "typography", category: "css" },
];
export default examplesData;
