const examplesData = [ 
	// { href: "http://localhost:3000/examples/atomic-example", name: "atomic-example", category: "css" },
	// { href: "http://localhost:3000/examples/box-model", name: "box-model", category: "css" },
	// { href: "http://localhost:3000/examples/checkbox-toggle.html", name: "checkbox-toggle.html", category: "css" },
	// { href: "http://localhost:3000/examples/checkbox-toggle2.html", name: "checkbox-toggle2.html", category: "css" },
	// { href: "http://localhost:3000/examples/flex-properties", name: "flex-properties", category: "css" },
	  { href: "http://localhost:3000/examples/inputs", name: "inputs", category: "css" },
	  { href: "http://localhost:3000/examples/inputs.html", name: "inputs.html", category: "css" },
	// { href: "http://localhost:3000/examples/loja-menu", name: "loja-menu", category: "css" },
	// { href: "http://localhost:3000/examples/relative-sizes", name: "relative-sizes", category: "css" },
	// { href: "http://localhost:3000/examples/relativity", name: "relativity", category: "css" },
	// { href: "http://localhost:3000/examples/responsive-grid", name: "responsive-grid", category: "css" },
	  { href: "http://localhost:3000/examples/responsive-images", name: "responsive-images", category: "css" },
	// { href: "http://localhost:3000/examples/responsive-tables", name: "responsive-tables", category: "css" },
	// { href: "http://localhost:3000/examples/scss", name: "scss", category: "css" },
	// { href: "http://localhost:3000/examples/scss.zip", name: "scss.zip", category: "css" },
	// { href: "http://localhost:3000/examples/selectors", name: "selectors", category: "css" },
	// { href: "http://localhost:3000/examples/sports-card", name: "sports-card", category: "css" },
	// { href: "http://localhost:3000/examples/typography", name: "typography", category: "css" },
];
export default examplesData;
